name: tonutils
description: Dart/Flutter library for TON blockchain
repository: https://github.com/novusnota/tonutils-dart
issue_tracker: https://github.com/novusnota/tonutils-dart/issues
version: 0.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  convert: ^3.1.1
  http: ^1.1.0
  pinenacl: ^0.5.1
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

topics:
  - cryptocurrency
  - crypto
  - ton
  - ton-blockchain
